### ISSUE TITLE
navbar-dropdown is-left

### ISSUE THREAD

**Issue by DJafari** [mohammadrafigh/bulma-rtl#2]
first of all, thanks for rtl this library
1. please update framework to last version
2. for `.navbar-dropdown` you must add a class with `is-left` name for align dropdown menu to the left, because right is default for rtl mode

https://github.com/mohammadrafigh/bulma-rtl/blob/9d8db498470a33f532a85e13a428c8b3205a1628/sass/components/navbar.sass#L341,L343

**Comment by mohammadrafigh** [comment]
@DJafari thanks for your report and sorry for delay, I was busy with my own works. I will take a look into it tonight and hopefully I can update the RTL to the latest version.

**Comment by mohammadrafigh** [comment]
@DJafari added is-left class in some places.

I updated master branch to 0.7.1 but still not tested and published in npm. I will test and publish it tomorrow.

Thanks
