### ISSUE TITLE
select "is-loading" positioning error

### ISSUE THREAD

**Issue by moataz1991** [mohammadrafigh/bulma-rtl#3]
Is it about Bulma or about the Docs? Bulma
Is it a bug/feature/question or do you need help? Bug
If it's a bug, is it a browser bug? No

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]
My **browser** is: Chrome

### Description

the loading indicator when we add the class "is-loading" in the **select** tag
has the wrong positioning 

### Steps to Reproduce

```
<div class="field">
       <label class="label">Type</label><div class="control">
       <div class="select is-loading">    <----- is-loading class !
              <select>
                      <option value="1">Type1</option>
                      <option value="2">Type2</option>
                      <option value="3">Dynamicly Added</option>
              </select>
       </div><p class="help">choose a type</p></div>
</div>
```

### Expected behavior

the loading indicator should be on the left side

### Actual behavior

the loading indicator in the right side also overlapping inside text

**Comment by mohammadrafigh** [comment]
I will take a look, thanks for reporting.

**Comment by mohammadrafigh** [comment]
is this still happening with latest release?
