### ISSUE TITLE
Classes `tag has-addons` and `is-delete` use LTR 

### ISSUE THREAD

**Issue by YacoubBelaoura** [mohammadrafigh/bulma-rtl#4]
This is about **Bulma**.

Is it about Bulma or about the Docs? : bulma

Is it a bug/feature/question or do you need help? :  bug

If it's a bug, is it a browser bug? : no

### Overview of the problem

 This is about the Bulma **CSS framework** 

 I'm using Bulma **version** [0.7.1] 
 My **browser** is: Chrome and Firefox

### Description

 the classes `tag has-addons` and `is-delete` are using the LTR direction

![screenshot at 2019-02-13 11-17-21](https://user-images.githubusercontent.com/18699402/52705263-c2aecb80-2f82-11e9-81a6-ca1f0da6f8b8.png)
![screenshot at 2019-02-13 11-16-41](https://user-images.githubusercontent.com/18699402/52705264-c2aecb80-2f82-11e9-8ddd-c166c2d85913.png)

### Expected behavior

![screenshot at 2019-02-13 11-19-09](https://user-images.githubusercontent.com/18699402/52705283-d22e1480-2f82-11e9-9076-4719e2ee5af5.png)
![screenshot at 2019-02-13 11-11-57](https://user-images.githubusercontent.com/18699402/52705285-d2c6ab00-2f82-11e9-87dd-f765151efd62.png)

**Comment by mohammadrafigh** [comment]
thank you for reporting. I will fix this in next releaase.

**Comment by mohammadrafigh** [comment]
is this still happening with latest release?
