### ISSUE TITLE
i18n support to change styles for LTR and RTL pages.

### ISSUE THREAD

**Issue by UtopiaBe** [mohammadrafigh/bulma-rtl#6]
This is about **Bulma**.

I need help!

Hello, I have i18n in my nuxt project!
And i need the style to go LTR when the website is in EN language.
I have user vuetify before, and it has a RTL: true/false option...

Do you have something like this?
Or you know any other solution?

**Comment by mohammadrafigh** [comment]
One way to doing so is dynamically modifying `<link rel="stylesheet" type="text/css" href="bulma-rtl.min.css">` to use bulma.min.css when the language is EN otherwise use bulma-rtl.min.css.

another way is deploying separate versions of your app in ltr and rtl versions.

**Comment by mohammadrafigh** [comment]
Closed due to inactivity
