### ISSUE TITLE
Wrong Import statement in the docs

### ISSUE THREAD

**Issue by mehdikazemnia** [mohammadrafigh/bulma-rtl#7]
This is about the Docs, more specifically, i've been having an issue with the import statement as it's recommended in the **README.md** file
As said in the file above i should use ``import 'bulma/css/bulma-rtl.css'`` to import the css file from `bulma-rtl`
The error i ran into was as described bellow:

> This dependency was not found:  bulma/css/bulma-rtl.css in ./src/main.js 

This package obviously gets installed on it's own name which is **bulma-rtl** not **bulma**
So i believe,
Instead of this:
``import 'bulma/css/bulma-rtl.css'``
This is the way to import `bulma-rtl`:
``import 'bulma-rtl/css/bulma-rtl.css'``

I've use **yarn** to install this dependency **and changing the import statement fixed the trouble**

**Comment by mohammadrafigh** [comment]
Oh thank you for reporting that. I will fix it.
