### ISSUE TITLE
rtl not set correctly after upgrade from 0.7.1 to 0.8.0

### ISSUE THREAD

**Issue by SMAH1** [mohammadrafigh/bulma-rtl#8]
This is bug.

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]
My **browser** is: firefox
I am sure this issue is **not a duplicate**?  yes

### Description

After upgrade bulma-rtl from 0.7.1 to 0.8.0,some of panel not **RTL**.
like:

![correct](https://user-images.githubusercontent.com/21136680/73595597-deaed280-452f-11ea-8fff-a54685f1b613.png)
![incorrect](https://user-images.githubusercontent.com/21136680/73595601-e1a9c300-452f-11ea-90a4-fd4872121ff0.png)

**Comment by mohammadrafigh** [comment]
Sorry I missed this issue, I will take a look, but this repo has been deprecated since Bulma would support RTL on the next release. I will try to fix this before that release.

**Comment by mohammadrafigh** [comment]
Bulma 0.9.0 has been released with RTL support. So I'm closing all issues and this repo is not going to be maintained anymore. thanks for your support.
