### ISSUE TITLE
Incorrect order in columns!

### ISSUE THREAD

**Issue by aryanbadiee** [mohammadrafigh/bulma-rtl#9]
Hi
The order of the each 'column' in 'columns' at bulma-rtl is incorrect
my code:
![1](https://user-images.githubusercontent.com/51372926/80475373-07dbd500-895e-11ea-810e-e602fbe1a9ad.png)

but my website:
![2](https://user-images.githubusercontent.com/51372926/80475428-1b873b80-895e-11ea-88ff-4cde1430f837.png)

I emphasize that in my css files, i don't change 'position' or 'layout'
So it happened with the bulma-rtl column

**Comment by mohammadrafigh** [comment]
Thanks I will take a look, but this repo has been deprecated since Bulma would support RTL on the next release. I will try to fix this before that release.

**Comment by aryanbadiee** [comment]
oh, I didn't read the first part of the 'readme' file
and i hope you succeed in developing RTL for bulma official package

**Comment by mohammadrafigh** [comment]
Bulma 0.9.0 has been released with RTL support. So I'm closing all issues and this repo is not going to be maintained anymore. thanks for your support.
